- include_vars: "{{ ansible_os_family }}.yml"

- shell: sudo service supervisor stop
  tags:
    - upgrade

- name: create sentry user
  action: user name=sentry group=1000 state=present

- name: ensure sentry var directory exists
  file:
    path: /var/sentry/
    state: directory
    owner: sentry

- name: ensure sentry etc directory exists
  file:
    path: /etc/sentry/
    state: directory
    owner: sentry

- name: install sentry and create virtualenv if needed
  pip:
    name: sentry[postgres]
    virtualenv: /var/sentry/ve
    virtualenv_site_packages: no
    
- name: install memcached
  pip:
    name: python-memcached
    virtualenv: /var/sentry/ve
    virtualenv_site_packages: no
    
- name: Copy sentry yaml configuration
  template: src=config.yml.j2 dest=/etc/sentry/config.yml
  notify: restart nginx
  tags:
    - upgrade

- name: Copy sentry python configuration
  template: src=sentry.conf.py.j2 dest=/etc/sentry/sentry.conf.py
  notify: restart nginx
  tags:
    - upgrade

- name: Copy nginx configuration for sentry
  template: src=nginx-sentry.conf.j2 dest=/etc/nginx/sites-available/sentry.conf owner={{ nginx_user }} group={{ nginx_group }}
  tags:
    - nginx

- name: Link nginx configuration for sentry
  file: src=/etc/nginx/sites-available/sentry.conf dest=/etc/nginx/sites-enabled/sentry.conf state=link owner={{ nginx_user }} group={{ nginx_group }}
  notify:
    - restart nginx
  tags:
    - nginx

- name: Copy supervisor configuration for sentry
  template: src=supervisor-sentry.conf.j2 dest=/etc/supervisor/conf.d/sentry.conf
  notify: 
    - reload supervisor
  tags:
    - upgrade

# Shell executable needs to be changed because Ubuntu uses /bin/dash when invoking /bin/sh, which doesn't support source. 
# see http://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell
- shell: /var/sentry/ve/bin/sentry --config=/etc/sentry/ upgrade --noinput
  notify:
    - restart nginx
    - reload supervisor
  tags:
    - upgrade
# # This is a bit of a hack to create a superuser automatically without interactive input. TODO: Create a proper python script for this!
# - name: create admin user
#   action: shell source ve/bin/activate && export SENTRY_CONF=/var/sentry/ && python -c "from sentry.utils.runner import configure; configure(); from django.db import DEFAULT_DB_ALIAS as database; from sentry.models import User; User.objects.db_manager(database).create_superuser('{{ superuser_sentry.username }}', '{{ superuser_sentry.email }}', '{{ superuser_sentry.password }}')" executable=/bin/bash chdir=/var/sentry
#   notify:
#     - restart nginx
#     - reload supervisor
    
- shell: sudo service nginx restart && sudo service supervisor start
  tags:
    - upgrade
